apiVersion: deploy.ibm.com/v1
kind: Environment
metadata:
  name: "zos_env_test"
  version: 1.0.0
spec:
  default_cics_cmci_action: "NEWCOPY"
  cics_sys_def:
     cicsplex: "CICSTS56"
     cmci_url: "http://ibm1.popup-mainframe.com:1490"
     cmci_user: ""
     cmci_password: ""
     cmci_action: "{{env.spec.default_cics_cmci_action}}"
     csd_group: "USER01"
  default_db2_sdsnload: "DSNC10.SDSNLOAD"
  default_package_jobcard: "BINDPKG JOB 'WD-PKGBIND',MSGLEVEL=(1,1),MSGCLASS=R,NOTIFY=&SYSUID"
  default_plan_jobcard: |
    BINDPLA JOB 'WD-PLANBIND',MSGLEVEL=(1,1),MSGCLASS=R,NOTIFY=&SYSUID
    /* ---
  default_db2_user: "{{ extra_vars.db2_user if extra_vars.db2_user is defined else 'IBMUSER' }}"
  default_db2_action: "REPLACE"
  db2_sys_def:
     package_maxrc: 4
     plan_maxrc: 4
     user: "{{ env.spec.default_db2_user }}"
     package: U01PKG
     plan: U01PLAN
     qualifier: EMP1
     subsys: DBCG
     package_jobcard: "{{env.spec.default_package_jobcard}}"
     plan_jobcard: "{{env.spec.default_plan_jobcard}}"
     package_action: "{{env.spec.default_db2_action}}"
     plan_action: "{{env.spec.default_db2_action}}"
     sdsnload: "{{env.spec.default_db2_sdsnload}}"
     plan_pklist: '*.U01PKG.*'
  common_pds_load_spec:
     type: LIBRARY
     primary_space: 10CYL
     secondary_space: 20CYL
     record_format: U
     record_length: 0
  common_pds_binary_spec:
     type: LIBRARY
     primary_space: 10CYL
     secondary_space: 20CYL
     record_format: FB
     record_length: 80
  hlq: "{{ extra_vars.hlq if extra_vars.hlq is defined else 'PRAKASH.OUT' }}"
  uss_root: "{{ extra_vars.uss_root if extra_vars.uss_root is defined else '/tmp/uss_root' }}"
  types:
    - pattern: .*\.LOAD$
      dataset: "{{ env.spec.hlq }}.LOADLIB"
      dataset_backup: "{{ env.spec.hlq }}.BACK.LOADLIB"
      spec: "{{ env.spec.common_pds_load_spec }}"
      is_load: True
      force_lock: True
      aliases: True
    - pattern: .*\.CICSLOAD$
      dataset: "{{ env.spec.hlq }}.LOADLIB"
      dataset_backup: "{{ env.spec.hlq }}.BACK.LOADLIB"
      spec: "{{ env.spec.common_pds_load_spec }}"
      is_load: True
      force_lock: True
      aliases: True
      cics_systems:
      - "{{ env.spec.cics_sys_def }}"
    - pattern: .*\.MAPLOAD$
      dataset: "{{ env.spec.hlq }}.LOADLIB"
      dataset_backup: "{{ env.spec.hlq }}.BACK.LOADLIB"
      spec: "{{ env.spec.common_pds_load_spec }}"
      is_load: True
      force_lock: True
      aliases: True
      cics_systems:
      - "{{ env.spec.cics_sys_def }}"
    - pattern: .*.DBRM$
      dataset: "{{ env.spec.hlq }}.DBRM"
      dataset_backup: "{{ env.spec.hlq }}.BACK.DBRM"
      spec: "{{ env.spec.common_pds_binary_spec }}"
      is_binary: True
      force_lock: True
      db2_systems:
      - "{{ env.spec.db2_sys_def }}"
